### PR TITLE
Support logical 'x' in weightedMean and friends

### PR DESCRIPTION
**Pull request by HughParsonage**
This seems like an easy win: I just add `if (is.logical(x)) x <- as.integer(x)` within the required functions.

### CODE REVIEW

**Comment by HenrikBengtsson** [comment]
Thanks for the PR.  A few comments though:

* All new features must be validated with packages tests before being introduced, e.g. it doesn't look like you added tests for `weigtedMedian()` and  `weigtedVar()`.  This is very important in order to prevent any type of mistakes from sneaking - regardless of how "obvious" the implementation appears - we've been bitten before and the cost of incorrect results can be quite big downstream.

* Mostly for my curiosity, what are some use cases where you end up with _logical_ and not integer values for which you want to use estimators median and variance?  I can see summing or averaging being useful for instance when "counting" indicator variables.  Basically, my question is, is the use case really valid or is it just that one ended up with logical variables when one instead should have read/created 0-1 integers in the first place?

* More importantly, we do not want to just do `x <- as.integer(x)`; that is very inefficient and as long as that is the only solution, I'd say it is better to leave that for the user to do explicitly (this is why it is as it is right now).  Instead, we want to have the implementation make use of the fact that logical (`FALSE`, `TRUE`, [`NA`](https://github.com/wch/r-source/blob/7ac84daceed027fc93f26ec4c76c244eed88421c/src/include/R_ext/Arith.h#L55-L56)) is identical to (`0L`, `1L`, [`NA_integer_`](https://github.com/wch/r-source/blob/7ac84daceed027fc93f26ec4c76c244eed88421c/src/include/R_ext/Arith.h#L55-L56)), which allows us to avoid having coerce and instead rely on the existing infrastructure for integers.  This "strategy" was used in the recent, similar updates to `colCumsums()`, cf. commit https://github.com/HenrikBengtsson/matrixStats/commit/ceb6a0f4647dcedfae39650d01e050c50b3eecd4.

**Comment by HughParsonage** [comment]
Thanks for the comments. I've tried to address them. I'm conscious that my supposedly 'easy win' has taken up more of your time than I intended and that my initial commit wasn't the cleanest. 

Happy to modify this pull request if you feel it's worth it, or I can make a new one.

**Comment by HenrikBengtsson** [comment]
Thank you very much for this updated PR.  I still haven't had time to look into it, but it's on my todo list.

PS. Nope, you're wasting anybody's time - any honest and thorough contribution is most welcome.

**Comment by HenrikBengtsson** [comment]
Thanks. This has finally been merged into the 'develop' branch.  We now have:

 * Now weightedMean() and weightedMedian() and the corresponding row- and
   column-based functions now accept logical 'x', where FALSE is treated as
   integer 0 and TRUE as 1.

In order for this to work also for `{col,row}WeightedMeans()`, I also had to add support for:

 * Now x_OP_y() and t_tx_OP_y() accept logical 'x' and 'y', where FALSE is
   treated as integer 0 and TRUE as 1.

**Pull request merged**
