### PR TITLE
Feature/subsetting A2

### PR DESCRIPTION
**Pull request by Dongcan-Jiang**
Milestone A2: Tests and R mockup implementation (subsetted computations).

### CODE REVIEW

**Comment by HenrikBengtsson** [comment]
Thanks.

I'm going through these updates and I'll try to minimize the differences that unreleated to subsetting between the `develop` and `feature/subsetting` branches.  Doing this, I discovered for instance the following update in [`rowWeightedMean.R`](https://github.com/Dongcan-Jiang/matrixStats/blob/feature/subsetting/R/rowWeightedMeans.R#L66-L68):
```r
-    if (any(!is.na(w) & w < 0)) {
+    if (any(w < 0)) {
       stop("Argument 'w' has negative weights.");
     }
```
There are few other updates like this.  Should this also have gone into `develop`, but was forgotten?  Did you add this for robustness, i.e. the current code does not support missing values in `w`, so at least it should be an error?

**Comment by Dongcan-Jiang** [comment]
@HenrikBengtsson As `weightedMean()` and `weighted.mean()` are able to handle `NA` weight, I made this change to let `rowWeightedMean()` behaves the same as `weighted.mean()` for each row.

**Comment by HenrikBengtsson** [comment]
Ah... now I see; my mistake, I basically read it as:
```r
    if (any(is.na(w) | w < 0)) {
      stop("Argument 'w' has negative weights.");
    }
```
I blame low blood sugar for that one.  I've now incorporated theses into the `develop` branch as well.

However, there's one more thing in `rowWeightedMean()` of `feature/subsetting`:
```r
     # Drop entries with zero weight?
-    idxs <- which(is.na(w) | w != 0);
+    idxs <- which(w != 0);
```
That drops columns with NA weights even when `na.rm=FALSE`.  Is that what we want?  Compare to:
```r
> weightedMean(x=1:3, w=c(1,NA,1), na.rm=TRUE)
[1] NA
```

**Comment by Dongcan-Jiang** [comment]
@HenrikBengtsson When `w = NA`, `(w!=0)` returns `NA`. `idxs <- which(is.na(w) | w != 0)` doesn't drop the columns with NA weights, because `which()` just chooses the indices whose value is `TRUE`.
```
# in branch feature/subsetting
> rowWeightedMeans(x=matrix(1:3,nrow=1), w=c(1,NA,1), na.rm=TRUE)                                          
[1] NA
> weighted.mean(1:3, w=c(1,NA,2))                                                                                                                                                                            
[1] NA

# in branch develop
> rowWeightedMeans(matrix(1:3, nrow=1), w=c(1,NA,2))                                                                                                                                                         
[1] 2.333333
```

**Comment by HenrikBengtsson** [comment]
Got it; my mistake.  I've made it explicit in the comment that NAs are _not_ dropped.

**Pull request merged**
